import { Injectable } from '@angular/core';
const findAnd = require("find-and");

@Injectable({
  providedIn: 'root'
})
export class ValidateService {

  constructor() { }

  validateMte(page: any): boolean {
    try {
      const currentDate = new Date();
      const usedDate = new Date(findAnd.returnFound(page, {
        "name": "DGC_USED_DATE"
      }).value);
      const returnDate = new Date(findAnd.returnFound(page, {
        "name": "DGC_RETURN_DATE"
      }).value);
      if (usedDate && (usedDate > currentDate)) {
        return false;
      }
      if (returnDate && (returnDate > currentDate)) {
        return false;
      }
      if (usedDate && (returnDate < currentDate)) {
        return false;
      }
    } catch (error) {
      return false;
    }

    return true;

  }
  page: any = {
    "id": "DGLN0000000000000105",
    "name": "DGPPackageAddMTE",
    "version": "208.8",
    "display": "Add M&TE",
    "type": 4000,
    "subType": 1000,
    "identity": "4000",
    "hideTitle": 0,
    "pageSizePercent": 0,
    "showNavigation": 1,
    "order": 0,
    "pageId": "DGLN0000000000000039",
    "attributes": [
      {
        "attrRow": 0,
        "attrColumn": 0,
        "attrOrder": 0,
        "id": "DGLN0000000000000928",
        "name": "DGC_INTERNAL_UNIQUE_ID",
        "attrColumnSpan": 0,
        "attrRowSpan": 0,
        "attrSize": 0,
        "dataType": 9009,
        "description": "Internal Unique Id used by tablet.",
        "displayAttr": 0,
        "displayType": 1000,
        "fontSize": 0,
        "isPackageInternalKey": 1,
        "isPackageKey": 0,
        "isRequired": 0,
        "isEditable": 0,
        "isScannable": 0,
        "isSortable": 0,
        "length": 32,
        "packageAttrDisplay": "Internal Unique Id",
        "packageAttrLabel": "Unique Id",
        "showShortLabel": 0,
        "hideLabel": 0
      },
      {
        "attrRow": 0,
        "attrColumn": 0,
        "attrOrder": 0,
        "id": "DGLN0000000000001029",
        "name": "DGC_ID",
        "attrColumnSpan": 0,
        "attrRowSpan": 0,
        "attrSize": 0,
        "dataType": 9009,
        "description": "Internal Key",
        "displayAttr": 0,
        "displayType": 1000,
        "fontSize": 0,
        "isPackageInternalKey": 0,
        "isPackageKey": 0,
        "isRequired": 0,
        "isEditable": 0,
        "isScannable": 0,
        "isSortable": 0,
        "length": 20,
        "packageAttrDisplay": "ID",
        "packageAttrLabel": "ID",
        "showShortLabel": 0,
        "hideLabel": 0
      },
      {
        "attrRow": 1,
        "attrColumn": 1,
        "attrOrder": 10,
        "id": "DGLN0000000000000422",
        "name": "DGC_MTE_ID",
        "attrColumnSpan": 1,
        "attrRowSpan": 1,
        "attrSize": 0,
        "dataType": 9009,
        "description": "M&TE ID",
        "displayAttr": 1,
        "displayType": 1000,
        "fontSize": 0,
        "isPackageInternalKey": 1,
        "isPackageKey": 0,
        "isRequired": 1,
        "isEditable": 1,
        "isScannable": 0,
        "isSortable": 0,
        "length": 32,
        "packageAttrDisplay": "M&TE ID",
        "packageAttrLabel": "M&TE ID",
        "showShortLabel": 0,
        "hideLabel": 0,
        "isValidateRequired": 1
      },
      {
        "attrRow": 2,
        "attrColumn": 1,
        "attrOrder": 0,
        "id": "DGLN0000000000000424",
        "name": "DGC_MTE_TAG",
        "attrColumnSpan": 1,
        "attrRowSpan": 1,
        "attrSize": 0,
        "dataType": 9009,
        "description": "M&TE Tag",
        "displayAttr": 0,
        "displayType": 1000,
        "fontSize": 0,
        "isPackageInternalKey": 0,
        "isPackageKey": 0,
        "isRequired": 0,
        "isEditable": 0,
        "isScannable": 0,
        "isSortable": 0,
        "length": 32,
        "packageAttrDisplay": "M&TE Tag",
        "packageAttrLabel": "M&TE Tag",
        "showShortLabel": 0,
        "hideLabel": 0
      },
      {
        "attrRow": 2,
        "attrColumn": 1,
        "attrOrder": 20,
        "id": "DGLN0000000000000423",
        "name": "DGC_MTE_NAME",
        "attrColumnSpan": 4,
        "attrRowSpan": 1,
        "attrSize": 0,
        "dataType": 9009,
        "description": "M&TE Name",
        "displayAttr": 1,
        "displayType": 1000,
        "fontSize": 0,
        "isPackageInternalKey": 0,
        "isPackageKey": 0,
        "isRequired": 0,
        "isEditable": 1,
        "isScannable": 0,
        "isSortable": 0,
        "length": 255,
        "packageAttrDisplay": "M&TE Name",
        "packageAttrLabel": "M&TE Name",
        "showShortLabel": 0,
        "hideLabel": 0
      },
      {
        "attrRow": 3,
        "attrColumn": 1,
        "attrOrder": 30,
        "id": "DGLN0000000000000429",
        "name": "DGC_CALIBRATION_DATE",
        "attrColumnSpan": 1,
        "attrRowSpan": 1,
        "attrSize": 0,
        "dataType": 9011,
        "description": "Calibration Date",
        "displayAttr": 1,
        "displayType": 3000,
        "fontSize": 0,
        "isPackageInternalKey": 0,
        "isPackageKey": 0,
        "isRequired": 0,
        "isEditable": 0,
        "isScannable": 0,
        "isSortable": 0,
        "length": 0,
        "packageAttrDisplay": "Calibration Date",
        "packageAttrLabel": "Cal. Date",
        "showShortLabel": 0,
        "hideLabel": 0
      },
      {
        "attrRow": 3,
        "attrColumn": 2,
        "attrOrder": 40,
        "id": "DGLN0000000000001671",
        "name": "DGC_CALIBRATION_DUE_DATE",
        "attrColumnSpan": 1,
        "attrRowSpan": 1,
        "attrSize": 0,
        "dataType": 9011,
        "description": "Calibration Due Date",
        "displayAttr": 1,
        "displayType": 3000,
        "fontSize": 0,
        "isPackageInternalKey": 0,
        "isPackageKey": 0,
        "isRequired": 0,
        "isEditable": 0,
        "isScannable": 0,
        "isSortable": 0,
        "length": 0,
        "packageAttrDisplay": "Calibration Due Date",
        "packageAttrLabel": "Cal. Due Date",
        "showShortLabel": 0,
        "hideLabel": 0
      },
      {
        "attrRow": 4,
        "attrColumn": 1,
        "attrOrder": 0,
        "id": "DGLN0000000000000433",
        "name": "DGC_MTE_RANGE",
        "attrColumnSpan": 1,
        "attrRowSpan": 1,
        "attrSize": 0,
        "dataType": 9009,
        "description": "M&TE Range Value",
        "displayAttr": 0,
        "displayType": 5000,
        "fontSize": 0,
        "isPackageInternalKey": 0,
        "isPackageKey": 0,
        "isRequired": 0,
        "isEditable": 0,
        "isScannable": 0,
        "isSortable": 0,
        "length": 32,
        "packageAttrDisplay": "Range",
        "packageAttrLabel": "Range",
        "showShortLabel": 0,
        "hideLabel": 0,
        "packageCodeName": "MTE_RANGE",
        "codes": [
          {
            "CODE": "1000",
            "DISPLAY": "AMP - Amperage"
          },
          {
            "CODE": "2000",
            "DISPLAY": "Mvdc - DC milivolts"
          },
          {
            "CODE": "3000",
            "DISPLAY": "Madc - DC miliamps"
          },
          {
            "CODE": "4000",
            "DISPLAY": "PSIG - Pounds per square inch"
          },
          {
            "CODE": "5000",
            "DISPLAY": "VDA - Volts AC"
          },
          {
            "CODE": "6000",
            "DISPLAY": "INH20 - Inches of Water"
          },
          {
            "CODE": "7000",
            "DISPLAY": "VDC - Volts DC"
          }
        ]
      },
      {
        "attrRow": 4,
        "attrColumn": 1,
        "attrOrder": 50,
        "id": "DGLN0000000000001586",
        "name": "DGC_USED_DATE",
        "attrColumnSpan": 1,
        "attrRowSpan": 1,
        "attrSize": 0,
        "dataType": 9011,
        "description": "Used Date",
        "displayAttr": 1,
        "displayType": 2000,
        "fontSize": 0,
        "isPackageInternalKey": 0,
        "isPackageKey": 0,
        "isRequired": 0,
        "isEditable": 1,
        "isScannable": 0,
        "isSortable": 0,
        "length": 0,
        "packageAttrDisplay": "Used Date",
        "packageAttrLabel": "Used Date",
        "showShortLabel": 0,
        "hideLabel": 0
      },
      {
        "attrRow": 4,
        "attrColumn": 2,
        "attrOrder": 60,
        "id": "DGLN0000000000000428",
        "name": "DGC_RETURN_DATE",
        "attrColumnSpan": 1,
        "attrRowSpan": 1,
        "attrSize": 0,
        "dataType": 9011,
        "description": "Return Date",
        "displayAttr": 1,
        "displayType": 2000,
        "fontSize": 0,
        "isPackageInternalKey": 0,
        "isPackageKey": 0,
        "isRequired": 0,
        "isEditable": 1,
        "isScannable": 0,
        "isSortable": 0,
        "length": 0,
        "packageAttrDisplay": "Return Date",
        "packageAttrLabel": "Ret. Dt.",
        "showShortLabel": 0,
        "hideLabel": 0
      },
      {
        "attrRow": 5,
        "attrColumn": 1,
        "attrOrder": 70,
        "id": "DGLN0000000000000425",
        "name": "DGC_COMMENTS",
        "attrColumnSpan": 4,
        "attrRowSpan": 4,
        "attrSize": 0,
        "dataType": 9009,
        "description": "Comments",
        "displayAttr": 1,
        "displayType": 1000,
        "fontSize": 0,
        "isPackageInternalKey": 0,
        "isPackageKey": 0,
        "isRequired": 0,
        "isEditable": 1,
        "isScannable": 0,
        "isSortable": 0,
        "length": 2000,
        "packageAttrDisplay": "Comments",
        "packageAttrLabel": "Comments",
        "showShortLabel": 0,
        "hideLabel": 0
      },
      {
        "attrRow": 6,
        "attrColumn": 1,
        "attrOrder": 0,
        "id": "DGLN0000000000000426",
        "name": "DGC_USED_IND",
        "attrColumnSpan": 1,
        "attrRowSpan": 1,
        "attrSize": 0,
        "dataType": 9003,
        "description": "Used Ind",
        "displayAttr": 0,
        "displayType": 4000,
        "fontSize": 0,
        "isPackageInternalKey": 0,
        "isPackageKey": 0,
        "isRequired": 0,
        "isEditable": 0,
        "isScannable": 0,
        "isSortable": 0,
        "length": 0,
        "packageAttrDisplay": "Used Ind",
        "packageAttrLabel": "Used?",
        "showShortLabel": 0,
        "hideLabel": 0
      },
      {
        "attrRow": 7,
        "attrColumn": 1,
        "attrOrder": 0,
        "id": "DGLN0000000000000427",
        "name": "DGC_RECORD_DATE",
        "attrColumnSpan": 1,
        "attrRowSpan": 1,
        "attrSize": 0,
        "dataType": 9011,
        "description": "Record Date",
        "displayAttr": 0,
        "displayType": 2000,
        "fontSize": 0,
        "isPackageInternalKey": 0,
        "isPackageKey": 0,
        "isRequired": 0,
        "isEditable": 0,
        "isScannable": 0,
        "isSortable": 0,
        "length": 0,
        "packageAttrDisplay": "Record Date",
        "packageAttrLabel": "Rec. Dt.",
        "showShortLabel": 0,
        "hideLabel": 0
      }
    ],
    "actions": [
      {
        "isCommonAction": 0,
        "isRowAction": 0,
        "isStatic": 0,
        "isToolbarAction": 0,
        "order": 9,
        "packageAction": "SAVE",
        "packageActionDetails": {
          "roles": [],
          "qualifications": [],
          "privileges": [],
          "status": []
        },
        "packageActionCode": 500500,
        "packageActionDisplay": "Save",
        "isCustom": 0,
        "actionApplicable": 3,
        "masterNotApplicable": 0,
        "loginReq": 0,
        "connectivityReq": 0,
        "checkoutReq": 0,
        "autoCheckinReq": 0,
        "confirmationReq": 0,
        "editReq": 0,
        "validOnCheckout": 0,
        "hideIfDisabled": 0,
        "supportMultiSelect": 0,
        "supportMultiStatus": 0,
        "packageCommentType": 0,
        "packageCommentOption": 0
      },
      {
        "isCommonAction": 0,
        "isRowAction": 0,
        "isStatic": 0,
        "isToolbarAction": 0,
        "order": 10,
        "packageAction": "CANCEL",
        "packageActionDetails": {
          "roles": [],
          "qualifications": [],
          "privileges": [],
          "status": []
        },
        "packageActionCode": 623000,
        "packageActionDisplay": "Cancel",
        "isCustom": 1,
        "actionApplicable": 0,
        "masterNotApplicable": 0,
        "loginReq": 0,
        "connectivityReq": 0,
        "checkoutReq": 0,
        "autoCheckinReq": 0,
        "confirmationReq": 0,
        "editReq": 0,
        "validOnCheckout": 0,
        "hideIfDisabled": 0,
        "supportMultiSelect": 0,
        "supportMultiStatus": 0
      }
    ],
    "searchAttributes": {
      "basic": [],
      "custom": []
    }
  };
}
