export enum SequenceTypes {
  ALPHABETICAL = 'ALPHABETICAL',
  NUMERIC = 'NUMERIC',
  BULLETS = 'BULLETS',
  DGSEQUENCES = 'DGSEQUENCES',
  Attachment  = "Attachment",
  STAR  = "STAR",
  SQUARE = "SQUARE",
  CIRCLE = "CIRCLE",
  CHECKMARK = "CHECKMARK",
  ARROW = "ARROW",
  CAPITALALPHABETICAL = 'CAPITALALPHABETICAL',
  ROMAN = 'ROMAN',
  CAPITALROMAN = 'CAPITALROMAN',
 
}
